### PR TITLE
 Add cubicCentimeters to Volume module

### PR DESCRIPTION
**Pull request by g-belmonte**
Hey there, @ianmackenzie !

I opened this MR implementing the cubic centimeters as an alias of milliliters, as I understood from https://github.com/ianmackenzie/elm-units/issues/52

Let me know your thoughts :smile:

### CODE REVIEW

**Comment by ianmackenzie** [comment]
Looks good, and thanks for adding tests as well! Only a couple very minor comments:

- I think it would probably make sense to list the two functions in the docs after `milliliters`/`inMilliliters` instead of after `cubicMeters`/`inCubicMeters`
- I think it might be useful to add a comment to each docs line like 'Alias for `milliliters`.'

**Comment by ianmackenzie** [comment]
Oh, and if you could add yourself to the `AUTHORS` file that would be great 🙂

**Comment by g-belmonte** [comment]
small doubt: at the module's `exposing`, should I leave the `cubicCentimeters` with the other cubic things, or after the milliliters, as in the body of the code?

**Comment by g-belmonte** [comment]
another doubt: should I add the cubicCentimeter to the list of unitary quantities at the end of the file?

**Comment by ianmackenzie** [comment]
Oh actually I think the issue is that `cubicCentimeters` and `inCubicCentimeters` need to be added to the `@docs` line after `milliliters`/`inMilliliters`; as long as you're using `elm-format` then they'll automatically be moved to the corresponding place in the module `exposing` clause. (You do have to make sure they've been added to the `exposing` clause _somewhere_ first, though.)

Good catch on adding `cubicCentimeter`! Yes, please do add that (to the code, `@docs` line and `exposing` clause - again, if you put it just after `milliliter` in the `@docs` line then `elm-format` should move it to the right place in the `exposing` clause.)

**Comment by g-belmonte** [comment]
Adjustments done! :smile: 

Checklist:
- [x] Add tests
- [x] Add cubic centimeter methods as milliliter alias
- [x] Add unitary quantity for cubic centimeter
- [x] Add new methods to the docs
- [x] Run elm-format

I hope I didn't miss anything :grin:

**Comment by ianmackenzie** [comment]
Looks great, thanks!

**Pull request merged**
