### PR TITLE
19 add constants module

### LINKED ISSUE #19: Add Constants module
This would be a central place to store conversion factors, useful for a couple reasons:

  - Avoid duplication when the same constants are used in multiple modules (e.g. `Mass` and `Volume` constants reused in `Density` module)
  - Be a single place to record what reference each constant was taken from (see #10)

### PR DESCRIPTION
**Pull request by katjam**
Fixes #19 

Starting to experiment with ways to express shared conversion factors and given constants vs. derived conversion factors (to be used/ shared as constants in modules)

## Looked at - to consider extract const:

 - [x] Acceleration
 - [x] Angle
 - [x] Angular Acceleration
 - [x] Angular Speed
 - [x] Area
 - [x] Capacitance
 - [x] Charge
 - [x] Current
 - [x] Density
 - [x] Duration
 - [x] Energy
 - [x] Force
 - [x] Inductance
 - [x] Length
 - [x] Mass
 - [x] Pixels
 - [x] Power
 - [x] Pressure
 - [x] Resistance
 - [x] Speed
 - [x] Substance Amount
 - [x] Temperature
 - [x] Voltage
 - [x] Volume

## Future: 
These are conversion factors but are well documented where used and cross ref'd. We might want to move to Constants - but @katjam figured this could be stage 2. Temperature constants are fairly well known and that module is special/ isolated from others.

 - [ ] parsec, astrounit, lightyear (Lengths)
 - [ ] gee (Acceleration)
 - [ ] pounds force (Force)
 - [ ] julian years (Duration)
 - [ ] long ton, short ton (Mass)
 - [ ] atmosphere in Pascals (Pressure)
 - [ ] metric, mechanical & electric horsepower (Power)

### CODE REVIEW

**Comment by katjam** [comment]
I've had a go replacing 0.0254 in the Length module with `ConversionFactor.metersPerInch` so we can discuss how that feels.

Unfortunately - if I replace `0.0000254` with `metersPerInch/1000` it returns `0.000025399999999999997` - I guess due to inaccuracy in Float maths? Should we be calculating with Integers and converting back to Floats? I suspect our accuracy is being effected elsewhere and we may not have noticed yet.

I've also assumed we are not exposing the ConversionFactors module to docs. Is that right?

**Comment by katjam** [comment]
I'm also open to @ianmackenzie pushing a commit to tidy up comments / layout in `ConversionFactors`. I'm not sure how to organise it so it's easy to see where stuff is coming from.

**Comment by ianmackenzie** [comment]
Hey @katjam, you're right that `ConversionFactors.elm` seems a bit tricky to find a good layout/organization for! I'd be curious to see what it would look like to have a `Constants.elm` file instead, since then it could largely follow the layout of the NIST standard and UK Weights and Measures Act pretty directly (restricting ourselves to the exact values only), e.g.

```elm
module Constants

-- from NIST unless otherwise specified

meter : Float
meter =
    1.0

centimeter : Float
centimeter =
    0.01 * meter

inch : Float
inch =
    0.0254 * meter

cubicInch : Float
cubicInch =
    inch * inch * inch

usLiquidGallon : Float
usLiquidGallon =
    231 * cubicInch

usLiquidQuart : Float
usLiquidQuart =
    0.25 * usLiquidGallon

bushel : Float
bushel =
    2150.42 * cubicInch

peck : Float
peck =
    0.25 * bushel

usDryQuart : Float
usDryQuart =
    0.125 * peck

liter : Float
liter =
    0.001 * cubicMeter

-- from UK Weights and Measures Act
imperialGallon : Float
imperialGallon =
    4.54609 * liter
```

(I'd prefer to use the NIST standard/Weights and Measures Act instead the less official Frink language units database.) In general in the above I tried to use the 'most exact'/'most fundamental' form of each unit, e.g. the US liquid gallon is defined as 231 cubic inches instead of 3.785411784 liters, although both of those are listed as exact conversions in the NIST standard. Individual modules might then look like

```elm
module Length

meters : Float -> Length
meters value =
    Quantity value

inMeters : Length -> Float
inMeters (Quantity length) =
    length

feet : Float -> Length
feet value =
    Quantity (value * Constants.foot)

inFeet : Length -> Float
inFeet (Quantity length) =
    length / Constants.foot
```

I'm not as concerned about things like `0.00254` vs `metersPerInch/1000` - I think floating point roundoff is pretty much unavoidable no matter what we do. I think the goal should be that all conversion factors are accurate to within floating point roundoff.

Oh, and the NIST PDF is currently inaccessible due to the US government shutdown, but you can get a copy [from the Internet Archive](https://web.archive.org/web/20171129045544/https://www.nist.gov/sites/default/files/documents/2017/04/28/AppC-12-hb44-final.pdf).

Finally, yes, I certainly wouldn't see the `ConversionFactors` module being documented/exposed! Especially since you can get any conversion factor you want using existing functionality, e.g.

```elm
litersPerUsLiquidGallon : Float
litersPerUsLiquidGallon =
    Volume.inLiters (Volume.usLiquidGallons 1)
```

**Comment by katjam** [comment]
@ianmackenzie :+1: That looks much better. Thanks.

**Comment by katjam** [comment]
@ianmackenzie Sounds sensible. I'll have time this weekend. I'm up to date with master again. I will look at how I derived the previous values. I think I have it recorded somewhere.

**Comment by katjam** [comment]
@ianmackenzie Sorry - I got caught up in life stuff at the weekend - not forgotten I have left this hanging though.

**Comment by ianmackenzie** [comment]
No worries at all @katjam! The whole point of merging in those small `Volume` constants changes was so that we could each work independently at our own pace...nothing is blocked on this, so take your time!

I *am* looking forward to seeing what everything looks like with the centralized constants, though =)

Oh, forgot to mention that I merged my `generalized-products` branch back to master yesterday, so you may want to update your branch at some point - I don't think there should be many (if any) conflicts, but let me know if you run into anything.

**Comment by katjam** [comment]
Thanks. Keep meaning to ask - are you coming over for Oslo Elm day next month?

**Comment by ianmackenzie** [comment]
Unfortunately no...I do love going to Elm conferences (I've been to elm-conf and presented at Elm Europe), but I'm also very conscious about the carbon impact of flying so I'm trying to limit my air travel.

Where are you based? I had London in my head but I can't remember why...if you *are* in London, though, I'll likely end up going there for work at some point so it would be great to grab coffee or something. And let me know if you ever happen to be in the Toronto area!

**Comment by ianmackenzie** [comment]
Oh, by the way: I'm getting close to a 2.0 release - any chance you could take a look at the [draft release notes](https://gist.github.com/ianmackenzie/d5cafed8e53a8f16e2c6c475eddd7267) and maybe skim the [current README](https://github.com/ianmackenzie/elm-units) to see if they make sense?

**Comment by katjam** [comment]
Yes - of course I can will skim now - and have a closer look over the next couple of days. I'll let you know if my skim throws up anything obvious.

Moving other conversation to slack.

**Comment by katjam** [comment]
@ianmackenzie How's this looking? Right direction? Feels a bit over the top with some of the definitions like square and cubed values in consts - but I think it reads clearly. I've not replaced the metric factors since I think those read easily as raw - but maybe we can at some point.

If it looks ok - I'll carry on replacing in this pattern.

Sorry I've not had more time to look at it recently.

**Comment by katjam** [comment]
In converting dry gallons to constants - I have found that NIST does not define as a Dry gallon so have opted for defining in terms of Pecks which follows more closely from the doc. However - this causes a fail on equality for 4 US dry quarts and 1 US dry gallon.

```
    0.004404882132153599
    ╷
    │ Expect.within Absolute 1e-12
    ╵
    0.00440488377086

```

See 430ac67955b3b140a24d9b4d4e26ace0f0aeb269

Sorry to bother you with niggles! Wondering what your opinion is.

**Comment by katjam** [comment]
screenshot_20190224_192216

**Comment by katjam** [comment]
Otherwise - going great. It reads so much better with this method of defining constants.

**Comment by ianmackenzie** [comment]
I think the issue is that the the US dry quart conversion factor should be 67.200625, not 67.2006...it's listed as 67.2006 in the first part of NIST Appendix C, but those are not exact values (see the first paragraph in the appendix). The exact values are the underlined ones in the tables in Section 4 - the first table on page C-11 has the exact dry quart conversion factor.

Sorry for the delay in replying - this one took a bit more careful investigation!

**Comment by katjam** [comment]
Thanks for taking the time to look into that for me. I should have realised that!

**Comment by ianmackenzie** [comment]
It could definitely be a lot more clear - it's extra confusing that Appendix C _also_ uses underlining to indicate survey foot or statute mile instead of international foot or mile. So just because you see some underlining in a conversion somewhere doesn't mean that conversion is exact...you have to check whether the underline is actually under the conversion factor value!

**Comment by katjam** [comment]
@ianmackenzie OK - I think this one is ready for review now!

Sorry about the long delay between activity. I may have gotten carried away with the Durations constants (last commit). Please feel free to alter anything I've done - if easier than communication back and forth.

Please also see my list of things to consider representing as constants in future. I tried to limit these changes to values that were used across more than one module for the most part.

**Comment by ianmackenzie** [comment]
Oops, somehow I totally missed the notification for your last comment when you said this was ready for review! And no problem at all, I've been pretty focused for the last while on building up a new documentation framework for `elm-geometry`. I'll try to take a look this weekend.

**Comment by katjam** [comment]
No problem at all. I was going to nudge next week but assumed you were either busy or missed it. I hope the geometry stuff going well.

**Comment by ianmackenzie** [comment]
I think this all looks great! I think your suggestions for other constants to move to `Constants.elm` all make sense - I'll open a new issue for those.

**Pull request merged**
