### PR TITLE
#6 Add Density module

### PR DESCRIPTION
**Pull request by katjam**
Awaiting decision on for which units we want conversions.

Candidates to consider from:
https://en.wikipedia.org/wiki/Density#Common_units
-and-
https://github.com/ianmackenzie/elm-units/blob/master/src/Volume.elm

@ianmackenzie thoughts?

### CODE REVIEW

**Comment by ianmackenzie** [comment]
Based on a quick look around various material property websites (and, to be honest, just some of my own personal experience), I think I'd start with:

  - Kilograms per cubic meter
  - Grams per cubic centimeter
  - Pounds per cubic inch
  - Pounds per cubic foot

I think that covers the most common cases, and it's easy enough to add more on request. How does that sound?

**Comment by katjam** [comment]
Looks good to me. As you say - we can add more easily, if need becomes apparent.

**Comment by ianmackenzie** [comment]
Might make sense to add a non-exposed Constants module...as well as avoiding duplication it would nice to have a central place to note down where each constant was taken from. Thoughts?

**Comment by katjam** [comment]
I was thinking exactly that but should we do as a new issue/ refactor?

**Comment by ianmackenzie** [comment]
Yes, I think so - just logged as #19. So do whatever is simplest for `Density` for now and we can migrate to a `Constants` module later. (If it's easiest to add a `Constants` module as part of this pull request and only add mass/volume constants in there for now, I think that would be OK - then we can migrate over other modules separately.)

**Comment by katjam** [comment]
@ianmackenzie Ready for review.

**Comment by ianmackenzie** [comment]
Sorry for the delay, still trying to get back into a normal routine - looks good!

**Pull request merged**
