### PR TITLE
Capacitance module added.

### PR DESCRIPTION
**Pull request by ukarim**

### CODE REVIEW

**Comment by ianmackenzie** [comment]
Looking good! Just made a few small changes, most significantly changing `picoFarads` to `picofarads` - I think this is a bit more accurate and consistent with what other `elm-units` modules do. Could you also add microfarads and nanofarads?

**Comment by ianmackenzie** [comment]
Oh, and go ahead and add yourself to the `AUTHORS` file as well! Don't have to provide e-mail address if you'd prefer not to, GitHub username is fine.

**Comment by ukarim** [comment]
@ianmackenzie I've just added functions for micro and nano farads.

**Comment by ianmackenzie** [comment]
(Also, apologies for the late reply - I'm in the middle of a move so I haven't had much access to my computer.)

**Pull request merged**
