### PR TITLE
#6 Add AngularSpeed module

### PR DESCRIPTION
**Pull request by katjam**
A WIP for continuous review/ collaboration.

@ianmackenzie I'll let you know when I think it's ready to go.

### CODE REVIEW

**Comment by ianmackenzie** [comment]
So the options I see for 'turns' vs 'revolutions' are:

  - Use 'turns' everywhere (including `turnsPerMinute`, ugh) - consistent with core, and concise
  - Use 'revolutions' everywhere (not bad, but inconsistent with core, and for something like "rotate a photo" I think that `Angle.turns 0.25` does in fact read a bit better than `Angle.revolutions 0.25`)
  - Use both terms as aliases for each other (maybe only in `AngularSpeed`), so have both `turnsPerSecond`, `revolutionsPerSecond`, `turnsPerMinute`, `revolutionsPerMinute` - then people can use whichever reads better in their specific situation
  - Use 'turns' in `Angle` and 'revolutions' in `AngularSpeed` - I rather like this, as 'revolutions' does sound a bit more 'dynamic' to me, but it is a bit jarring that `Angle` would have 'degrees', 'radians', 'turns' and `AngularSpeed` would have 'degrees', 'radians', 'revolutions'

Thoughts? Are there other possible approaches I've missed?

**Comment by katjam** [comment]
I think you've covered it. I like:

> Use both terms as aliases for each other (maybe only in AngularSpeed), so have both turnsPerSecond, revolutionsPerSecond, turnsPerMinute, revolutionsPerMinute - then people can use whichever reads better in their specific situation

I think it's OK to only alias as revolutions in `Angular speed` - so people can choose what's natural. I think this solution would be most intuitive and cause least confusion.

**Comment by ianmackenzie** [comment]
I should have looked at the code first =) Your approach with `turnsPerSecond` and `revolutionsPerMinute` is also quite reasonable...it seems like the main question is "where do you draw the border between 'turns' and 'revolutions'"? (Between core and `elm-units`? Between `Angle` and `AngularSpeed`? Within `AngularSpeed`, between per-second and per-minute measures?) Or don't draw a border at all, and just introduce 'revolutions' as an alternative in `AngularSpeed`?

I'm happy to go ahead with 'revolution' aliases in `AngularSpeed` for now and see how that feels.

**Comment by ianmackenzie** [comment]
I guess the only other question is how will this affect `AngularAcceleration` (should it also have aliases for everything, just use 'revolutions'....?). But perhaps that's not a big concern, as it will likely be used much more rarely than `AngularSpeed`.

**Comment by katjam** [comment]
Ha ha - yeah I tried it on to see how it played to have one as turns/sec and revs/min.

But I think let's do both for both - just in this module.

> just introduce 'revolutions' as an alternative in AngularSpeed?

Will consider `AngularAcceleration` when we get there - since we'll know how the aliases feel implemented in `AngularSpeed`

Not sure how much time I'll have this week - but will try to keep momentum up.

**Comment by katjam** [comment]
@ianmackenzie I think this is ready.

**Comment by ianmackenzie** [comment]
Looks great, thanks!! (Apologies for the delayed response - I'm in the middle of a move and haven't had much access to my computer.)

**Comment by katjam** [comment]
(Now it's my turn to apologise for delay) been busy and now away from home for a week - but hoping to get a WIP up for AngularAcceleration in a day or 2.

**Pull request merged**
